### PR TITLE
fix: Migrate Postgres to sqlite

### PR DESCRIPTION
**Pull request by davidrui-dev**

### CODE REVIEW

**Comment by vespergo** [comment]
great job, i'm going to check it out tomorrow.

**Comment by davidrui-dev** [comment]
Thanks, I will wait your feedback.

**Comment by vespergo** [comment]
Since this will be disruptive to CI/CD on vercel which is currently set to pull from master. I'm going to merge it onto it's own branch for interviews.

**Comment by davidrui-dev** [comment]
Could  you please let me know next hiring process?

**Comment by davidrui-dev** [comment]
Could you please let me know feedback for the code and our interview?
Thank you. Regards.
David.

**Comment by vespergo** [comment]
Hi David, 

Can you send me an email via gmail and we can pick up the conversation there?

**Comment by davidrui-dev** [comment]
I am not sure your contact address.
It's my email address.
david.rui.work@gmail.com
Look forward to hearing from you.
Thank you.

**Pull request merged**
