### PR TITLE
Added basic theme toggle using context API

### PR DESCRIPTION
**Pull request by bwanamaina**
Added basic logic for toggling `theme` using React `context` API.
Added test button under `app/ui/dashboard/nav-links.tsx` component.

Screenshot 2024-01-10 at 12 12 41

### CODE REVIEW

**Comment by vespergo** [comment]
Thanks for providing the code. I'll check it out tomorrow.

**Comment by vespergo** [comment]
Were you able to test the code? It wasn't working when I pulled it locally.

**Comment by bwanamaina** [comment]
I added that logic to a [component](https://github.com/vespergo/reactstarter/blob/master/app/dashboard/customers/page.tsx) that wasn't implemented in the main dashboard, to fix this, I've moved that logic to the `sidenav`  component. 
Kindly pull the latest and test again. 
Screenshot 2024-01-10 at 12 12 41

**Comment by vespergo** [comment]
ok i'll check again this morning.

**Comment by vespergo** [comment]
making some adjustments to this.

**Pull request closed without merging**
